version: '3.5'


services:
  db:
    env_file: 
      - db-variables.env
    container_name: db
    hostname: ${DB_HOST}
    build:
        context: ./repository/
        dockerfile: Dockerfile
    networks:
      - ${NETWORK}
    stdin_open: true 
    tty: true
      
  rest:
    env_file: 
      - rest-variables.env
    container_name: rest
    hostname: ${REST_HOST}
    build:
        context: ./rest/
        dockerfile: Dockerfile
    networks:
      - ${NETWORK}
    ports:
      - "8080:8080"
    stdin_open: true 
    tty: true
    depends_on:
      - db
  
  drone_hub:
    env_file: 
      - drone-hub-variables.env
    container_name: drone_hub
    hostname: ${DRONE_HUB_HOST}
    build:
      context: ./drone_hub/
      dockerfile: Dockerfile
    networks:
      - ${NETWORK}
    stdin_open: true 
    tty: true
    depends_on:
      - rest
      - db

networks:
  dis_sys:
    name: ${NETWORK}
    external: true
