# Generated by Erlang.mk. Edit at your own risk!

src/active_drone_handler.erl:: src/records.hrl; @touch $@
src/db_initializer.erl:: src/records.hrl; @touch $@
src/delivery_handler.erl:: src/records.hrl; @touch $@
src/spawn_recovery_handler.erl:: src/records.hrl; @touch $@

COMPILE_FIRST +=
